package com.attendance.academic_courses.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme - Gray to White
val md_theme_light_primary = Color(0xFF4A6572)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0E0E0)
val md_theme_light_onPrimaryContainer = Color(0xFF263238)
val md_theme_light_secondary = Color(0xFF607D8B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFECEFF1)
val md_theme_light_onSecondaryContainer = Color(0xFF263238)
val md_theme_light_tertiary = Color(0xFF78909C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCFD8DC)
val md_theme_light_onTertiaryContainer = Color(0xFF263238)
val md_theme_light_error = Color(0xFFB00020)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFDECEF)
val md_theme_light_onErrorContainer = Color(0xFF690012)
val md_theme_light_background = Color(0xFFFAFAFA)
val md_theme_light_onBackground = Color(0xFF263238)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF263238)
val md_theme_light_surfaceVariant = Color(0xFFEEEEEE)
val md_theme_light_onSurfaceVariant = Color(0xFF455A64)
val md_theme_light_outline = Color(0xFF78909C)
val md_theme_light_outlineVariant = Color(0xFFB0BEC5)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme - Purple
val md_theme_dark_primary = Color(0xFFBB86FC)
val md_theme_dark_onPrimary = Color(0xFF121212)
val md_theme_dark_primaryContainer = Color(0xFF3700B3)
val md_theme_dark_onPrimaryContainer = Color(0xFFE6DDFB)
val md_theme_dark_secondary = Color(0xFF03DAC6)
val md_theme_dark_onSecondary = Color(0xFF000000)
val md_theme_dark_secondaryContainer = Color(0xFF018786)
val md_theme_dark_onSecondaryContainer = Color(0xFFB3F1EA)
val md_theme_dark_tertiary = Color(0xFFCF6679)
val md_theme_dark_onTertiary = Color(0xFF000000)
val md_theme_dark_tertiaryContainer = Color(0xFF9A3F4C)
val md_theme_dark_onTertiaryContainer = Color(0xFFF5D6DC)
val md_theme_dark_error = Color(0xFFCF6679)
val md_theme_dark_onError = Color(0xFF000000)
val md_theme_dark_errorContainer = Color(0xFFB1384E)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1E1E1E)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF2D2D2D)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_outlineVariant = Color(0xFF444444)
val md_theme_dark_scrim = Color(0xFF000000)
